In [2]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time

In [3]:
mixer.init()
sound = mixer.Sound('alarm.wav')

In [4]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")
model = load_model(os.path.join("models", "model.h5"))

In [5]:
lbl=['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

In [6]:
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
        
       #Condition for Close
        
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            
            #print("Close Eyes")
            
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            
            #print("Open Eyes")
            
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 1s 1s/step
[[0.01107666 0.9889233 ]]
1/1 [==============================] - 0s 40ms/step
[[1.5656214e-04 9.9984336e-01]]
1/1 [==============================] - 0s 42ms/step
[[4.0523473e-06 9.9999595e-01]]
1/1 [==============================] - 0s 51ms/step
[[0.11231844 0.8876816 ]]
1/1 [==============================] - 0s 45ms/step
[[0.958774   0.04122599]]
1/1 [==============================] - 0s 51ms/step
[[0.06641541 0.93358463]]
1/1 [==============================] - 0s 47ms/step
[[2.0997413e-06 9.9999785e-01]]
1/1 [==============================] - 0s 41ms/step
[[2.9021598e-06 9.9999714e-01]]
1/1 [==============================] - 0s 42ms/step
[[0.48355037 0.51644963]]
1/1 [==============================] - 0s 48ms/step
[[0.26315168 0.7368483 ]]
1/1 [==============================] - 0s 51ms/step
[[0.08642371 0.91357625]]
1/1 [==============================] - 0s 51ms/step
[[7.4679892e-06 9.9999249e-01]]
1/1 [==============================]

1/1 [==============================] - 0s 43ms/step
[[0.9093551  0.09064495]]
1/1 [==============================] - 0s 47ms/step
[[0.01588682 0.98411316]]
1/1 [==============================] - 0s 39ms/step
[[0.02818091 0.97181904]]
1/1 [==============================] - 0s 46ms/step
[[0.9952662  0.00473386]]
1/1 [==============================] - 0s 39ms/step
[[0.88485897 0.11514107]]
1/1 [==============================] - 0s 45ms/step
[[0.07015952 0.9298405 ]]
1/1 [==============================] - 0s 45ms/step
[[0.19822139 0.8017786 ]]
1/1 [==============================] - 0s 41ms/step
[[0.9803535  0.01964651]]
1/1 [==============================] - 0s 47ms/step
[[0.08370627 0.91629374]]
1/1 [==============================] - 0s 41ms/step
[[0.06955019 0.9304498 ]]
1/1 [==============================] - 0s 37ms/step
[[0.14424627 0.8557537 ]]
1/1 [==============================] - 0s 35ms/step
[[0.9159909  0.08400904]]
1/1 [==============================] - 0s 45ms/step
[[0.90581775

1/1 [==============================] - 0s 44ms/step
[[0.3583837 0.6416164]]
1/1 [==============================] - 0s 48ms/step
[[0.98620343 0.0137966 ]]
1/1 [==============================] - 0s 41ms/step
[[0.42959696 0.57040304]]
1/1 [==============================] - 0s 45ms/step
[[0.30618528 0.69381475]]
1/1 [==============================] - 0s 51ms/step
[[4.5146875e-04 9.9954849e-01]]
1/1 [==============================] - 0s 40ms/step
[[0.1431448 0.8568552]]
1/1 [==============================] - 0s 45ms/step
[[0.1462012  0.85379887]]
1/1 [==============================] - 0s 40ms/step
[[0.7168425  0.28315756]]
1/1 [==============================] - 0s 39ms/step
[[6.946140e-05 9.999305e-01]]
1/1 [==============================] - 0s 47ms/step
[[3.987708e-04 9.996013e-01]]
1/1 [==============================] - 0s 48ms/step
[[0.01869505 0.98130494]]
1/1 [==============================] - 0s 43ms/step
[[4.5261387e-04 9.9954730e-01]]
1/1 [==============================] - 0s 42ms/s